name: Build macOS

on:  
  push:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Dependencies
      run: brew install ninja hdf5 pkg-config

    - name: Checkout
      uses: actions/checkout@v3


    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/_build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build . 
      working-directory: ${{ github.workspace }}/_build

